# Generated by Django 2.2.3 on 2020-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Hindi', 'H'), ('English', 'E'), ('Punjabi', 'P')], max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('album', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=500)),
            ],
        ),
    ]
