# Generated by Django 2.2.3 on 2020-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Punjabi', 'Punjabi')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=255)),
                ('playlist_curator', models.CharField(max_length=255)),
                ('playlist_art', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('song_url', models.CharField(max_length=1000)),
                ('album_id', models.IntegerField()),
                ('song_artist', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='song_to_playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField()),
                ('playlist_id', models.IntegerField()),
            ],
        ),
    ]
