# Generated by Django 2.2.3 on 2020-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default='', upload_to='audiofile'),
            preserve_default=False,
        ),
    ]
