# Generated by Django 2.2.3 on 2020-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_songs_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio_file',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='songs',
            name='category',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Punjabi', 'Punjabi')], max_length=100),
        ),
    ]
